### ISSUE TITLE
Issue updating to use 1.6.0 version with zip_tricks 5.6.0

### ISSUE THREAD

**Issue by brettwgreen** [fringd/zipline#101]
Not really sure what's going on here... the last published version on rubygems lists dependency on zip_tricks as:
```
[zip_tricks](https://rubygems.org/gems/zip_tricks) ~> 4.8, < 6
```

Yet when I run bundler with a gemfile like this:
```
gem 'zip_tricks', '~> 5.6.0'
gem 'zipline', '~> 1.6'
```

It tells me:
```
Could not find compatible versions

Because zipline >= 1.6.0 depends on zip_tricks >= 4.8, < 5.A
  and Gemfile depends on zip_tricks ~> 5.6.0,
  zipline >= 1.6.0 cannot be used.
So, because Gemfile depends on zipline ~> 1.6,
  version solving has failed.
```

Where is this `< 5.A` thing coming from? I don't see that anywhere?

Also see you're moving to a different underlying library anyway but that version doesn't seem to be published yet.

**Comment by julik** [comment]
I know this possibly does not answer your question directly, but can you try installing `zipline` from this GH repo? There was a switch to zip_kit where the dependency situation should improve. The explicit zip_tricks dependency should also be removed then.

**Comment by brettwgreen** [comment]
I did that but, of course, that means moving to zip_kit... unfortunately, we use another gem that is still bound to zip_tricks (xlsxstream). Wasn't crazy about having both in my dependencies, but I think I'll do a pull request over there and see if I can get that somewhat dormant repo to merge it.

I was more curious about the weird 5.A dependency... seemed like something wrong with how gem was pushed to rubygems repo because I could not explain it.

**Comment by julik** [comment]
5.A is very weird - maybe something with Bundler gem dep resolution. There was never such a version released. However - zip_tricks and zip_kit _can_ be used in the same codebase - they do not share constants. Another gem is just another gem 😄  maybe that can work for you in the meantime?

**Comment by julik** [comment]
@brettwgreen the release of zipline with zip_kit is out. You should be able to use it alongside any dependency which still uses zip_tricks.
