### ISSUE TITLE
Support for CarrierWave::Storage::AWSFile

### ISSUE THREAD

**Issue by dayweek** [fringd/zipline#17]
Hi, I'm using carrierwave-aws gem and internally it is using `CarrierWave::Storage::AWSFile`. The problem is that the URL can't be fetched by curl since the file is not public. I made a fix for that but it has to download the file first. What do you think? I plan to create a pull request soon.

Commit: https://github.com/dayweek/zipline/commit/60f08bd90d6d87639d11808bcf3cfffd97f22f7a

Thanks
David

**Comment by fringd** [comment]
I thought that even for non public files you still got a temporary url that was something like "myfile?secretToken=a3ac3acff32329"

maybe it's possible to curl after all?

**Comment by fringd** [comment]
see my comment on your fork

**Comment by fringd** [comment]
I made some changes and testesd out s3 with paperclip and carrierwave with private urls. should work now!
