### ISSUE TITLE
Doesn't start streaming right away

### ISSUE THREAD

**Issue by moayman** [fringd/zipline#19]
Hello,

Thanks a lot for your work.

I am having a problem, I am trying to zip files from my amazon S3 and the `.lazy` doesn't seem to 

> "allows us to begin sending the download immediately instead of waiting to download everything"

I am testing using the localhost. Will it be any different on heroku? (I don't think so)

Thanks again,

Ayman Salah

**Comment by fringd** [comment]
what container are you using? Are you using unicorn or something that supports streaming?

**Comment by moayman** [comment]
I am not using unicorn or anything else. I have only included the code you provided on the readme.

Thanks for your reply.

**Comment by moayman** [comment]
`include ActionController::Streaming
  include Zipline
  require 'open-uri'

  def serve_folder

    avatars = [  [ 'https://amazon.s3-us-west-2.amazonaws.com/CU/FOE/CHS/PPC/P/PEN402/sections/section_1.ppt', 'avatars/section_1.ppt' ],  [ 'https://amazon.s3-us-west-2.amazonaws.com/CU/FOE/CHS/PPC/P/PEN402/sections/section_2.pdf', 'avatars/section_2.pdf' ]  ]

    file_mappings = avatars.lazy.map { |url, path| [open(url), path] }
    zipline(file_mappings, 'avatars.zip')

  end`

**Comment by moayman** [comment]
My heroku settings says that the Stack is cedar-14.

**Comment by moayman** [comment]
How can I setup unicorn?

**Comment by fringd** [comment]
did you get it figured out?

**Comment by moayman** [comment]
Well I am a newbie. I am sorry for bothering you.
I didn't know what is unicorn and whatever else u mentioned in the readme.
Hours of reading... Now I know and have successfully switched to using Puma locally and on Heroku and everything works well.

Thanks a lot man.

**Comment by fringd** [comment]
yay, no problem :)
