### ISSUE TITLE
RFC: Migrate this to zip_tricks

### ISSUE THREAD

**Issue by julik** [fringd/zipline#23]
So, this gem has been very inspiring for me and we did go out and build [our own streaming ZIP library](https://github.com/WeTransfer/zip_tricks) that we use massively. We had to rewrite ours to work without Rubyzip recently because of all the intricacies and overrides we had to introduce. We also initially omitted data descriptor use (what you have used here) because it was a bit problematic in the beginning with the OSX archive utility. Now everything works fine on our end.

So, as a gesture of gratitude, we can fulfill items 2 and 3 on your TODO list if you let me :-) the only thing that zip_tricks depends on having Ruby 2.1 due to massive use of keyword arguments. If this is not a problem I can prepare you a PR and replace your hacks-on-hacks-on-hacks with something a little more.. formal 🚀 

We can also make use of our size precompute to set the right `Content-Length`.

Let me know ;-)

**Comment by fringd** [comment]
thanks so much! Fixed a few little things and pushed a new gem!
