### ISSUE TITLE
Using local files with carrierwave will not work properly

### ISSUE THREAD

**Issue by abcang** [fringd/zipline#28]
I am using a local file with carrierwave, but specifying an object directly does not work properly.
So, I created and specified a file object using the file path.

```rb
# It does not work properly.
def index
  users = User.all
  files =  users.map{ |user| [user.avatar, "#{user.username}.png"] }
  zipline( files, 'avatars.zip')
end
```

```rb
# It works correctly.
def index
  users = User.all
  files =  users.map{ |user| [File.open(user.avatar.current_path), "#{user.username}.png"] }
  zipline( files, 'avatars.zip')
end
```

It is probably because url is used preferentially in the write_file method.
https://github.com/fringd/zipline/blob/master/lib/zipline/zip_generator.rb#L44

**Comment by fringd** [comment]
Yeah that sucks I'd like the above example to work... how can you tell if a carrierwave file is local file?

**Comment by ABCanG** [comment]
For local files, the class of `file` is `CarrierWave::SanitizedFile`.
Also, in the case of a remote file, the class of `file` is `CarrierWave::Storage::Fog::File`.

```rb
# local
user.avatar.file.class # => CarrierWave::SanitizedFile

# remote
user.avatar.file.class # => CarrierWave::Storage::Fog::File
```

Or, there is also a way to verify the `_storage`.

```rb
# local
user.avatar._storage # => CarrierWave::Storage::File

# remote
user.avatar._storage # => CarrierWave::Storage::Fog
```

I noticed another thing. `Carrierwave::SanitizedFile` does not correspond to `IO.copy_stream`.
https://github.com/carrierwaveuploader/carrierwave/issues/1959

So, when using a local file, write_file does not work even if lowering the priority of url.

**Comment by fringd** [comment]
Do you think you could try to fix it by changing the normalize method to check if file is a CarrierWave::SanitizedFile and if it is, just set file = file.file

It would be much appreciated!

**Comment by ABCanG** [comment]
`CarrierWave::SanitizedFile` does not correspond to `IO.copy_stream`. So, it seems necessary to convert it to File as shown below.

```rb
def normalize(file)
  if file.respond_to?(:file) && file.file.is_a?(CarrierWave::SanitizedFile)
    file = File.open(file.file.path)
  end
  file
end
```

Also, `CarrierWave::Uploader::Base` has a `read` method, so it seems necessary to be careful.

```rb
user.avatar.respond_to?(:read) # => true
is_io?(user.avatar) # => true
```

**Comment by savef** [comment]
I just ran into this situation myself and have noticed that CarrierWave has two ways to create SanitizedFiles, one seems to provide direct access to the local file and the other provides a StringIO, see:
```ruby
irb(main):109:0> user.avatar.file
=> #<CarrierWave::SanitizedFile:0x0055cd5b4eb2d0 @file="/path/to/file.png", @original_filename=nil, @content_type="image/png">
irb(main):110:0> user.avatar.sanitized_file
=> #<CarrierWave::SanitizedFile:0x0055cd5d14c6b8 @file=#<StringIO:0x0055cd5d14c870>, @original_filename="file.png", @content_type="image/png">
```

Interestingly this means we can map like so in our controller:
`files = users.map { |user| [user.avatar.sanitized_file.file, "#{user.username}.png"] }`
Which is at least a small improvement on the working solution from the original post.

-----

> Also, CarrierWave::Uploader::Base has a read method, so it seems necessary to be careful.

I'm not very knowledgeable about CarrierWave, why is being careful important here? What is the downside of Zipline calling `CarrierWave::Uploader::Base#read` if we pass our `Uploader` object straight in?

**Comment by julik** [comment]
@abcang FWIW for something to work with `IO.copy_stream` it needs to support `#read`. If `CarrierWave::SanitizedFile` doesn't you probably should be able to open a PR with them so that they add it. Apparently `SanitizedFile` _does_ support `#to_file` which, by Ruby conventions, _must_ give you a real to-filesystem File object. Just don't forget to close it afterwards.

**Comment by fringd** [comment]
hey I looked at your pull request and it looked good, but it inspired me to rework the normalization code and tests a bit. I've pushed a new commit, could you try using the github version in your project and test it out?
