### ISSUE TITLE
When using StringIO instead of files; not lazy at all...!

### ISSUE THREAD

**Issue by fatuhoku** [fringd/zipline#29]
It takes about 2 seconds to generate a PDF. I want the zip download to start streaming as soon as each PDF is ready. However I did not want to store the PDFs, because they rely on live data from the database.

So, I put the PDF generation routine into a lazy array, in the hope that zipline would trigger PDF generation, and STREAM that same PDF immediately afterwards by wrapping it with a StringIO.

However, ZipTricks instead appears to want to iterate over all the files, triggering PDF rendering eagerly.

How can I ensure these PDFs get generated lazily?

**Comment by fringd** [comment]
Hmmm looks like you could probably just use ZipTricks directly... I haven't looked at their repository recently, but it looks like they've evolved to totally subsume the functionality of this repo (which is getting to be poorly maintained, sorry)... check out this part of their readme: https://github.com/WeTransfer/zip_tricks#diving-in-send-some-large-csv-reports-from-rails

**Comment by fatuhoku** [comment]
Hey @fringd thanks for the response — I did have a go at using zip_tricks but I ended up with the same issue. The block that I thought was going to be deferred due to `lazy` was being executed eagerly.

**Comment by fringd** [comment]
what's your code look like?

**Comment by julik** [comment]
@fatuhoku please post some example code and we will figure out what's going on. I think your issue is rather on the _output_ side of things than on the Zip side of things (if you are saying that StringIO's are involved)

**Comment by fatuhoku** [comment]
Never mind — I've fixed the issue by using a background job + sidekiq. Cheers!
