### ISSUE TITLE
Wrong include in the documentation?

### ISSUE THREAD

**Issue by Kjir** [fringd/zipline#33]
Hi,
I'm not really sure about this, but according to my tests with a plain example, the include in the README is wrong:

```ruby
class HomeController
  include ActionController::Streaming

  def index
    10.times do
      response.stream.write("Hello, world\n")
      sleep 1
    end
  ensure
    response.stream.close
  end
```

This will not stream the response. If, on the other hand, I substitute the include with `include ActionController::Live` the response will stream. It will also trigger this bug: rails/rails#31200

In the documentation for zip_tricks they also suggest to use `ActionController::Live`: https://github.com/WeTransfer/zip_tricks#diving-in-send-some-large-csv-reports-from-rails

I haven't been able to try it out with zipline, so this is the reason I have no certainty, but I gave you my evidence that seems to point to an issue. Have you verified otherwise?

**Comment by fringd** [comment]
well it used to work, but it's possible something changed. Do you know which server this was with? puma? something else?

**Comment by Kjir** [comment]
Yes, I use puma.

How do you test that the live streaming actually works? Because with the setup in the readme the download works, but it is not a live streaming.

**Comment by fringd** [comment]
It was definitely working at some point. Maybe something changed, but If you haven't actually tested it out with zipline and seen it take a long time to start sending bytes, I'm pretty sure it is working.

**Comment by fringd** [comment]
I'm using an older API where I return an iterable response... Maybe I should change it to use Live, but I don't think it's a big issue.

**Comment by Kjir** [comment]
So I did some testing and yes, the streaming actually works correctly.
Following the documentation in zip_tricks will trigger the rails/rails#31200 bug, but in the case of zipline since you use a different API this doesn't happen.

FYI here's how I tested it (the download start immediately and the streams...):

```ruby
class DownloadController < ApplicationController
  include ActionController::Streaming
  include Zipline

  def index
    images = 10000.times.lazy.map do |i|
      ['app/assets/images/big.jpg', "images/big#{i}"]
    end.lazy.map { |path, name| [File.open(path), name] }

    zipline images, 'images.zip'
  end
end
```

**Comment by fringd** [comment]
thanks for investigating this!
