### ISSUE TITLE
Bad File/Stream in AWS S3 with CarrierWave

### ISSUE THREAD

**Issue by KBuild** [fringd/zipline#40]
Hello!
At first, thanks to make this project. I really happy to use this library, and sorry to my poor English skill.

Bad File/Stream error occurred when CarrierWave::Uploader::Base has a url starts with "//" like a "//s3-ap-northeast-1.amazonaws.com/somebucket/folder/~~~". (set url with carrierwave's asset host config)

In my guess maybe Curl(and some other programs) deny to process a wrong web url starts with "//". (But works on web browsers)

and also `open(url starts with "//")` can be fail cause of this situation, so I guess [this issue](https://github.com/fringd/zipline/issues/39) also have occurred the same reason

So I propose a solution.
1)Add a url correction method or 2)Seperate a error name when url is bad or 3)Allow passing parameter [user_corrected_url, file_name] map to zip_generator initialize method

**Comment by fringd** [comment]
Ah interesting. I'll happily merge a PR that looks reasonable. Is there another method on those objects that gives a fully qualified url? Those urls are probably not specified so they can match the protocol of the website your user is visiting. But we are getting them from a server not a browser. So we need to explicitly choose http it https.

**Comment by KBuild** [comment]
Thank you for replying.

In my case, I make a map(for first parameter that send to zipline method) as like a ``[open(file.to_s.sub(/^\/\//, 'https://')), file_name]``
so, I can clear my problem.

But someone can confuse when give a error name as "Bad File Stream". And I also agree to making a fully qualified url is hard.
So how about add a new error like a "Bad URL Format; you should make full concrete url with protocol"?

Should I do make a PR?
