### ISSUE TITLE
Support for modifcation date

### ISSUE THREAD

**Issue by aried3r** [fringd/zipline#41]
Hey! I was wondering if you'd be open for a modification to this library to add support for modification date which was added to zip_tricks as well https://github.com/WeTransfer/zip_tricks/pull/43/files.

**Comment by fringd** [comment]
Yeah I'm up for it. what would the API be for the user, though?

**Comment by fringd** [comment]
I dunno. How do you set the date in zip tricks? Is there just an option
object there?

**Comment by aried3r** [comment]
zipline uses
https://github.com/fringd/zipline/blob/974ba903c5a26dd8a075faa4c9fe19482a10e7a5/lib/zipline/zip_generator.rb#L61

and zip_tricks added an optional named parameter to this method
https://github.com/RTrampov/zip_tricks/blob/c1fe786ad72561a3f3d924f5f659d2642bd68365/lib/zip_tricks/streamer.rb#L310
```Ruby
def write_deflated_file(filename, modification_time: Time.now.utc)
```
(see the PR I linked in the OP)

So it should work with just supplying a third optional element in the array:
```Ruby
=> [['file', 'name']].each { |file, name, optional| puts file; puts name; puts optional.nil? }
file
name
true

=> [['file', 'name', Time.now]].each { |file, name, optional| puts file; puts name; puts optional }
file
name
2019-01-22 16:45:14 +0100
```

That's how it's used here, except for the optional parameter: https://github.com/fringd/zipline/blob/974ba903c5a26dd8a075faa4c9fe19482a10e7a5/lib/zipline/zip_generator.rb#L18

**Comment by fringd** [comment]
Maybe we should add an optional 3rd argument with any options. We can pass them along to write_deflated_file.

API would end up like this:

```ruby
    files =  users.map{ |user| [user.avatar, "#{user.username}.png", modification_time: Time.now.utc] }
```

**Comment by fringd** [comment]
sorry I'm just repeating you. :P I'm skimming too fast.

Anyways, Yes! I would love a PR with this feature added.
