### ISSUE TITLE
Replace curb with Net:HTTP

### ISSUE THREAD

**Issue by aried3r** [fringd/zipline#51]
Hey! Would you be open to a PR that replaces curb (which requires native extensions) with Net:HTTP directly? If I understood correctly, the Net:HTTP code is only slightly more involved and would remove the need to have native extensions compiled.

https://github.com/fringd/zipline/blob/eff1c493ab9eb91a56406aec1b389a64cd5121dd/lib/zipline/zip_generator.rb#L68-L74

Untested, taken from the Ruby docs
```rb
uri = URI(the_remote_url)

Net::HTTP.start(uri.host, uri.port) do |http|
  request = Net::HTTP::Get.new uri

  http.request request do |response|
    response.read_body do |chunk|
      writer_for_file << chunk
    end
  end
end
```
https://ruby-doc.org/stdlib-2.6.3/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Streaming+Response+Bodies

**Comment by fringd** [comment]
sure I'd merge that if it supports everything curb does. Would it support https?

**Comment by aried3r** [comment]
It appears so, in the case of `.start` I believe we have to set `use_ssl` ourself, unlike `.get_request` which sets it automatically.

https://github.com/ruby/ruby/blob/ruby_2_3/lib/net/http.rb#L471-L484

According to [this](https://books.google.at/books?id=bJkznhZBG6gC&pg=PA502&lpg=PA502&dq=net::http.get_response+block&source=bl&ots=AnN0e2mXPI&sig=ACfU3U3H-8w6WOfuR8tQ9M0iFbJYgWnhiA&hl=en&sa=X&ved=2ahUKEwjqvuW7g7rjAhWMxIsKHfQcAsoQ6AEwBHoECAgQAQ#v=onepage&q=net%3A%3Ahttp.get_response%20block&f=false) and the official documentation `.get_request` also supports the block form, so something like this should work:

```rb
uri = URI(the_remote_url)

Net::HTTP.get_response(uri) do |response|
  response.read_body do |chunk|
    writer_for_file << chunk
  end
end
```

Ruby 2.3 documentation, since that's the lowest supported by this gem.
https://docs.ruby-lang.org/en/2.3.0/Net/HTTP.html#class-Net::HTTP-label-HTTPS

**Comment by fringd** [comment]
If you can get it all working smoothly I'm all for it. It's been a while since I made this decision so any reasons for choosing curb or not choosing Net::Http are long forgotten.
