### ISSUE TITLE
undefined local variable or method error.

### ISSUE THREAD

**Issue by holden** [fringd/zipline#57]
Under the recommended usage for ActiveStorage I keep getting the error:

```
NameError (undefined local variable or method `headers' for main:Object)
```

## Controller

```
    respond_to do |format|
      format.html
      format.js
      format.zip {
        unless @activity_log.blank?
          event_assets = @activity_log.event_assets
          files = event_assets.map { |x| [x.asset, x.asset.filename] }
          zipline(files, "#{@activity_log.name}.zip")
        end
      }
    end
```

It worked fine when I passed it the URLs directly but it also requred me to set the `ActiveStorage::Current.host` 

```
files = event_assets.map { |x| [x.asset.service_url, x.asset.filename.to_s] }
```

Rails 5.2
ActiveStorage 5.2.3
Zipline 1.1.1

**Comment by fringd** [comment]
It sounds like maybe ActiveStorage is misconfigured? It should be able to just figure out the service_url

**Comment by fringd** [comment]
Maybe there's something I'm missing in my ActiveStorage support though... do you know what class type x.asset is?

**Comment by fringd** [comment]
I believe that it should work, and use download(&block) to get the data... try using download |data| {...}

if that doesn't work you probably have something misconfigured? maybe you just need to configure the host somewhere?

**Comment by holden** [comment]
Yes, the class type of asset is `ActiveStorage::Attached::One`. Ok, I'll double-check our configuration and try messing around with it a bit more.

Thanks

**Comment by fringd** [comment]
Cool let me know either way! If you think you know what the fix is, send me a PR. This gem is very small and should be sorta easy to understand.

**Comment by fringd** [comment]
holden did you figure out what the issue was?

**Comment by fringd** [comment]
closing this because it's gone quiet.

**Comment by jeremysenn** [comment]
I'm having a similar issue.

```
files = [
  ["http://localhost:3000/api/v1/images/1898063/display", "ticket_131889_id_1898063.jpg"], 
  ["http://localhost:3000/api/v1/images/1898062/display", "ticket_131889_id_1898062.jpg"]
]

zipline(files, "test.zip")
```

Which returns: 

`NameError (undefined local variable or method 'headers' for main:Object)`

Any help is greatly appreciated!

Ruby 2.6.3p62
Rails 5.2.3
Zipline (1.2.1)

**Comment by fringd** [comment]
what does your whole controller look like?

**Comment by jeremysenn** [comment]
I ended up just using zip_tricks directly. Thank you.

**Comment by fringd** [comment]
Okay thanks for the update. I wonder if this is something in a new version
of rails maybe? i'd expect headers to be available in the controller.
