### ISSUE TITLE
uninitialized constant Admin::RolesController::Zipline

### ISSUE THREAD

**Issue by henron1** [fringd/zipline#58]
Getting this error when I include the lib in the class per the readme.

**Comment by fringd** [comment]
what's the error?

**Comment by henron1** [comment]
uninitialized constant Admin::RolesController::Zipline

**Comment by fringd** [comment]
what's Admin::RolesController? is that a rails thing?

**Comment by henron1** [comment]
It's a controller I'm trying to use zipline in. It's not liking the "include Zipline"

**Comment by fringd** [comment]
I'm not sure exactly what's going on, but it's looking for Zipline in that namespace... can you paste the full file?

**Comment by fringd** [comment]
is the gem definitely installed?

**Comment by henron1** [comment]
`def role_legal_agreement_download
    urls = []
    @role.people_casted.each do |person|
      person.agreements.each do |agreement|
        data = open(agreement.pdf.service_url)
        urls.push(data)
      end
    end
    zipline(urls, 'archive.zip')
  end
`

**Comment by henron1** [comment]
I'm now getting an error `Read error: #<NoMethodError: undefined method `tr' for nil:NilClass`

**Comment by fringd** [comment]
did you get it fixed?
