### ISSUE TITLE
Accept a directory path

### ISSUE THREAD

**Issue by mecampbellsoup** [fringd/zipline#63]
This is a feature request/proposal.

Would you be amenable to changing zipline's behavior to facilitate usage like the following:

```ruby
path = '/mnt/path/to/some/directory/with/lots/of/files'
zipline(path, 'my-big-zipfile.zip')
```
?

**Comment by swiknaba** [comment]
That should already work, without too much code. Just on mobile ATM, so no formatting or accurate syntax, but did you try sth like:

```ruby
files = Dir["/path/to/search/**/*.jpg"] # or any regex you need
zipline("archive.zip", files.map { |f| [f, f.split("/").last }
```

Just read through this file, it is not that complex: https://github.com/fringd/zipline/blob/master/lib/zipline/zip_generator.rb#L74

**Comment by mecampbellsoup** [comment]
Yep, naturally I figured this out after I opened this issue and forgot to update here. Thanks!
