### ISSUE TITLE
New release to publish latest changes to Gemspec

### ISSUE THREAD

**Issue by Flauschbaellchen** [fringd/zipline#72]
Hello,

I just wanted to upgrade to Rails 6.1 and saw that zipline was downgraded from 1.2.1 to 0.0.7 in the process:
```
Fetching zipline 0.0.7 (was 1.2.1)
Installing zipline 0.0.7 (was 1.2.1)
```

In my search, I saw that the Gemspec has already been adjusted (9043b6edf3161740e4e5c09b03ed1a24e26df16d :+1:) .
Is there already a date when a new version will be released?
Currently, Rails 6.1 always installs a very old zipline version, even if you were previously on a current version.

With kind regards~

**Comment by fringd** [comment]
Hey pushed a new version @1.3.0 let me know if there are any issues

**Comment by Flauschbaellchen** [comment]
Thank you for the fast response and your support, @fringd.
Everything is working and my Rails project updated successfully to zipline 1.3.0
