### ISSUE TITLE
wrong number of arguments (given 2, expected 0)

### ISSUE THREAD

**Issue by OGsoundFX** [fringd/zipline#77]
I have been looking around for solutions but couldn't find any. I hope it's OK to ask here.
I have been getting this error message while trying to implement zipline:
`wrong number of arguments (given 2, expected 0)`

Here is my very simple method, as stated in the readme file:
`require 'zipline'`

`def zipline`
    `tracks = [['https://www.ogsoundfx.com/NeWsfXsHoPbAmSfx/testing/Aggressive_Beast_1.mp3', 
    "Aggressive_Beast_1.mp3"], ['https://www.ogsoundfx.com/NeWsfXsHoPbAmSfx/testing/Aggressive_Beast_2.mp3', 
    "Aggressive_Beast_2.mp3"], ['https://www.ogsoundfx.com/NeWsfXsHoPbAmSfx/testing/Aggressive_Beast_3.mp3', 
    "Aggressive_Beast_1.mp3"]]
    zipline(tracks, 'tracks.zip')`
  `end`

Sorry if this is a stupid question, I am pretty new to all this.
Thanks!
Olivier

**Comment by Petercopter** [comment]
@OGsoundFX This is probably it. https://github.com/fringd/zipline/issues/75 

In the meantime, I'd recommend using https://github.com/WeTransfer/zip_tricks, which powers zipline.

**Comment by OGsoundFX** [comment]
Thank you very much I will definitely look into that!

**Comment by courtsimas** [comment]
I have the same issue. @OGsoundFX did you ever solve this? 👀

**Comment by OGsoundFX** [comment]
No I didn't, I ended up using `rubyzip` gem instead :)

**Comment by courtsimas** [comment]
I’ll have to do the same. Thanks @OGsoundFX

**Comment by OGsoundFX** [comment]
Let me know if you run into any problems. I haven't touched that part of the code in a long time but maybe I can help :)
