### ISSUE TITLE
Chrome multiple download wierd freeze...

### ISSUE THREAD

**Issue by ConfusedVorlon** [fringd/zipline#94]
Firstly - thanks for this gem. It's _so_ much better than my previous approach of downloading things, zipping them and sending them up again to S3

I did find one super-wierd thing though.

If I kick off more than one download on chrome - then they both freeze.

Initially - I assumed this was a problem at the server, but multiple downloads from different browsers, or indeed multiple downloads from Safari are fine.

So - this may just be a Chrome bug, but I wondered if you had any ideas or insight? It would be nice to have a fix.

This is Chrome 120.0.6099.216 (Official Build) (arm64) on Mac.

Thanks.

**Comment by ConfusedVorlon** [comment]
additional wierdness - while this is frozen, then any normal pages on the domain fail to load as well (in Chrome)

**Comment by julik** [comment]
Could you verify whether Chrome connects using just one connection and HTTP/2 of some kind, or HTTP 1.1? It might be that there is some demultiplexing versus other browsers which means that there is just 1 connection open to your server from Chrome, and multiple to other browsers

**Comment by ConfusedVorlon** [comment]
Checking now - and I don't see the issue.
It's a different computer, and updated Chrome, but I can't replicate it.
fwiw - the site does support http2, and the downloads (now at least) are using http2

Thanks for responding
